services:
  api:
    build:
      context: .
      target: base     # 👈 IMPORTANT
    container_name: diabetes_api
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    restart: unless-stopped